apiVersion: apps/v1
kind: Deployment
metadata:
  name: coordinator
  labels:
    service: coordinator
spec:
  replicas: 1
  selector:
    matchLabels:
      service: coordinator
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: coordinator
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - image: "{{ .Values.image.coordinator_repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          command: ["cape"]
          args: ["coordinator", "start", "--file", "/etc/coordinator/coordinator-config.yaml"]
          name: coordinator
          ports:
            - containerPort: {{ .Values.port }}
          volumeMounts:
            - name: config
              mountPath: "/etc/coordinator"
              readOnly: true
      {{ if (.Values.dockerSecret)}}
      imagePullSecrets:
        - name: {{ .Values.dockerSecret }}
      {{ end }}
      volumes:
        - name: config
          configMap:
            name: coordinator-config-map
