apiVersion: apps/v1
kind: Deployment
metadata:
  name: coordinator
  labels:
    service: coordinator
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      service: coordinator
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: coordinator
      # used for local development to always upgrade the
      # deployment when running helm upgrade
      # TODO revist for production deployments
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - image: "{{ .Values.image.coordinator_repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          command: ["cape"]
          args: ["coordinator", "start", "--file", "/etc/coordinator/coordinator-config.yaml",
                 "--instance-id", "{{ .Values.instance_id }}"]
          name: coordinator
          ports:
            - containerPort: {{ .Values.port }}
          volumeMounts:
            - name: config
              mountPath: "/etc/coordinator"
              readOnly: true
      {{ if (.Values.dockerSecret)}}
      imagePullSecrets:
        - name: {{ .Values.dockerSecret }}
      {{ end }}
      volumes:
        - name: config
          configMap:
            name: coordinator-config-map
