kind: Service
apiVersion: v1
metadata:
  name: coordinator
  labels:
    service: coordinator
spec:
  ports:
  - name: "coordinator-api"
    port: 8081
  selector:
    service: coordinator
  type: NodePort
status:
  loadBalancer: {}
