apiVersion: batch/v1
kind: Job
metadata:
  name: cape-coordinator-migration
spec:
  template:
    spec:
      containers:
      - image: "{{ .Values.image.coordinator_migration_repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: Always
        name: updater
        env:
          - name: "CAPE_DB_URL"
            value: "{{ .Values.db.url }}"
      restartPolicy: Never
status: {}
