apiVersion: v1
kind: Secret
metadata:
  name: {{ template "cape.configSecret" . }}
  namespace: {{ template "cape.namespace" . }}
  labels:
    {{- include "cape.labels" . | nindent 4 }}
type: Opaque
data:
  coordinator-config.yaml: {{ toYaml .Values.config | b64enc }}
