apiVersion: batch/v1
kind: Job
metadata:
  name: update-db
spec:
  template:
    spec:
      containers:
      - image: "{{ .Values.image.update_repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: Always
        name: updater
        env:
          - name: "CAPE_DB_URL"
            value: "{{ .Values.db.url }}"
      restartPolicy: Never
status: {}
