# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - go mod download
    # Meant to be run on github actions ubuntu runner
    - sudo apt install -y zip
    - zip -r capeprivacy-cape-postgres-{{.Version}}.zip coordinator/migrations/
builds:
- env:
  - CGO_ENABLED=0
  goos:
    - linux
    - windows
    - darwin
  main: ./cmd
  goarch:
    - amd64
  binary: cape
  flags:
     - -i
     - -v
  ldflags:
     - -s -w -X github.com/capeprivacy/cape/version.Version={{.Version}} -X github.com/capeprivacy/cape/version.BuildData={{.Date}}
release:
  extra_files:
    - glob: capeprivacy-cape-postgres-{{.Version}}.zip
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
