serviceAccount:
  create: true
  name: ""

service:
  type: "ClusterIP"
  port: 80
  targetPort: 3000
  annotations: {}
  labels: {}
  portName: service

labels: {}
annotations: {}

replicas: 1
deploymentStrategy:
  type: RollingUpdate

# podLabels: {}
# podAnnotations: {}

admin:
  existingSecret: ""

image:
  repository: capeprivacy/cape
  tag: latest
  pullPolicy: IfNotPresent

## Assign a PriorityClassName to pods if set
# priorityClassName

## Use an alternate scheduler
# schedulerName:


## Override the deployment namespace
namespaceOverride: ""

## Override the deployment name
nameOverride: ""

## Override the generated full name
fullnameOverride: ""
