image:
  coordinator_repository: localhost:5000/capeprivacy/cape
  update_repository: localhost:5000/capeprivacy/update
  tag: latest

db:
  url: postgres://postgres:dev@postgres-postgresql:5432/postgres

# port to run the coordinator on
port: 8080
