serviceAccount:
  create: true
  name: ""

service:
  type: "ClusterIP"
  port: 8080
  targetPort: 3000
  uiPortName: ui
  uiPort: 80
  uiTargetPort: 80
  annotations: {}
  labels: {}
  portName: service

labels: {}
annotations: {}

replicas: 1
deploymentStrategy:
  type: RollingUpdate

# podLabels: {}
# podAnnotations: {}

admin:
  existingSecret: ""

image:
  repository: capeprivacy/cape
  tag: latest
  pullPolicy: IfNotPresent

includeUI: false
uiImage:
  repository: capeprivacy/cape-ui
  tag: latest
  pullPolicy: IfNotPresent

## Assign a PriorityClassName to pods if set
# priorityClassName

## Use an alternate scheduler
# schedulerName:


## Override the deployment namespace
namespaceOverride: ""

## Override the deployment name
nameOverride: ""

## Override the generated full name
fullnameOverride: ""

config:
  db:
    addr: "postgres://postgres:dev@postgres-cape-postgresql:5432/cape"
  port: 8080
  root_key: ul0b9qQONZDn4kLNgULl3WJOZEhBqDjT1YK-kgceFUU
  version: 1
  cors:
    enable: true
    allow_origin:
      - http://localhost:8080
