image:
  repository: localhost:5000/capeprivacy/cape
  tag: latest

service:
  type: "NodePort"
  port: 8081
  nodePort: 30881

# the secret containing the token the connector uses
# to authenticate with the coordinator
token_secret: connector-secret

# the url to the coordinator deployed inside of the cluster. since we're using
# nodeport services this is a static address instead of a service dns
coordinator_url: http://coordinator-cape-coordinator.default.svc:8080
serviceAccount:
  create: true
