image:
  coordinator_repository: localhost:5000/capeprivacy/cape
  update_repository: localhost:5000/capeprivacy/update
  seed_repository: localhost:5000/capeprivacy/customer_seed
  tag: latest

db:
  url: postgres://postgres:dev@postgres-postgresql:5432/cape

seed_db:
  url: postgres://postgres:dev@postgres-postgresql:5432/postgres
