serviceAccount:
  create: true
  name: ""

image:
  repository: localhost:5000/capeprivacy/cape
  tag: latest
  pullPolicy: Always

uiImage:
  repository: localhost:5000/capeprivacy/cape-ui
  tag: latest
  pullPolicy: Always

# used for the config file the coordinator takes
config:
  db:
    addr: postgres://postgres:dev@postgres-cape-postgresql:5432/cape
  port: 8080
  root_key: ul0b9qQONZDn4kLNgULl3WJOZEhBqDjT1YK-kgceFUU
  version: 1
  cors:
      enable: true
      allow_origin:
        - 'localhost:8080'
  user:
    name: cape_user
    email: cape_user@mycape.com
    password: capecape

service:
  type: "NodePort"
  port: 8080
  targetPort: 8080
  nodePort: 30880
  uiPortName: "cape-ui"
  uiPort: 80
  uiNodePort: 30882
  annotations: {}
  labels: {}
  portName: service

instance_id: local-dev

labels: {}
annotations: {}

replicas: 1
deploymentStrategy:
  type: RollingUpdate

# podLabels: {}
# podAnnotations: {}

admin:
  existingSecret: ""

## Assign a PriorityClassName to pods if set
# priorityClassName

## Use an alternate scheduler
# schedulerName:


## Override the deployment namespace
namespaceOverride: ""

## Override the deployment name
nameOverride: ""

## Override the generated full name
fullnameOverride: ""
