# Override values for the bitnami/postgres chart
# See: https://github.com/bitnami/charts/tree/master/bitnami/postgresql
postgresqlUsername: postgres
postgresqlPassword: dev
postgresqlDatabase: customer

# Run postgres as a NodePort service so we can expose it on the Helm Pack 
service:
    type: NodePort
    nodePort: 30544
    port: 5434