apiVersion: batch/v1
kind: Job
metadata:
  name: test
spec:
  template:
    spec:
      containers:
      - name: test
        image: dropoutlabs/cape-test:latest
        env:
          - name: CAPE_DB_URL
            value: "postgres://postgres:dev@-db-postgresql.default.svc.cluster.local:5432/postgres?sslmode=disable"
      backoffLimit: 1
      restartPolicy: Never
