apiVersion: batch/v1
kind: Job
metadata:
  name: seed-db
spec:
  template:
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: Always
        name: seeder
        env:
          - name: "CAPE_DB_URL"
            value: "{{ .Values.db.url }}"
      restartPolicy: Never
