apiVersion: batch/v1
kind: Job
metadata:
  name: seed-db
spec:
  template:
    spec:
      containers:
        - image: "{{ .Values.image.seed }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          name: updater
          env:
            {{ if (.Values.db.passwordSecret )}}
            - name: "CAPE_DB_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
            {{ end }}
            - name: "CAPE_DB_URL"
              value: "{{ .Values.db.url }}"
      restartPolicy: Never
status: {}
