FROM capeprivacy/base:latest

ENV VERSION="0.0.0"

COPY . ./

RUN mage build:binary

# We copy the built binary into a new alpine container so we can package a
# container with the smallest footprint possible
FROM alpine:3.11

RUN apk --no-cache add ca-certificates
COPY --from=0 /go/src/github.com/capeprivacy/cape/bin/cape /usr/local/bin/cape

ENTRYPOINT ["sh", "-c", "cape"]
