// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"net/url"

	"github.com/dropoutlabs/cape/database"
	"github.com/dropoutlabs/cape/primitives"
	"github.com/manifoldco/go-base64"
)

type AddSourceRequest struct {
	Label       string  `json:"label"`
	Credentials url.URL `json:"credentials"`
}

type AssignRoleRequest struct {
	RoleID       database.ID `json:"role_id"`
	AssignmentID database.ID `json:"assignment_id"`
}

type AuthSessionRequest struct {
	Signature base64.Value `json:"signature"`
}

type CreateRoleRequest struct {
	Label       string        `json:"label"`
	IdentityIds []database.ID `json:"identity_ids"`
}

type DeleteRoleRequest struct {
	ID database.ID `json:"id"`
}

type DeleteSessionRequest struct {
	Token base64.Value `json:"token"`
}

type LoginSessionRequest struct {
	Email string `json:"email"`
}

type NewUserRequest struct {
	Name      string                        `json:"name"`
	Email     string                        `json:"email"`
	PublicKey base64.Value                  `json:"public_key"`
	Salt      base64.Value                  `json:"salt"`
	Alg       primitives.CredentialsAlgType `json:"alg"`
}
