apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "cape.fullname" . }}-migration
spec:
  template:
    spec:
      containers:
      - name: seeder
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        command: [ "cape" ]
        args: [ "update", "coordinator/worker/migrations" ]
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
          - name: "CAPE_DB_URL"
            value: "{{ .Values.config.db.addr }}"
      restartPolicy: Never
