FROM golang:1.13.7-alpine

WORKDIR /root/

COPY --from=dropoutlabs/cape:latest /go/src/github.com/dropoutlabs/cape/bin bin
COPY --from=dropoutlabs/cape:latest /go/src/github.com/dropoutlabs/cape/tools/seed migrations

CMD ["./bin/cape", "update"]