FROM golang:1.13.7-alpine

WORKDIR /root/

COPY --from=capeprivacy/cape:latest /go/src/github.com/capeprivacy/cape/bin bin
COPY --from=capeprivacy/cape:latest /go/src/github.com/capeprivacy/cape/tools/seed migrations

CMD ["./bin/cape", "update"]
