apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: controller
  labels:
    service: controller
spec:
  replicas: 1
  strategy:
    rollingUpdate:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: controller
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: Always
        name: controller
        env:
          - name: "DB_BACKEND"
            value: "{{ .Values.db.backend }}"
          - name: "POSTGRES_ADDR"
            value: "{{ .Values.db.postgres.addr }}"
        command: ["./privacy", "controller", "start"]
        ports:
        - containerPort: 8081
status: {}
