apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: controller
  labels:
    service: controller
spec:
  replicas: 1
  strategy:
    rollingUpdate:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: controller
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: Always
        name: controller
        env:
          {{ if (.Values.db.passwordSecret )}}
          - name: "DB_PASSWORD"
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: password
          {{ end }}
          - name: "DB_ADDR"
            value: "{{ .Values.db.addr }}"
        command: ["./privacy", "controller", "start"]
        ports:
        - containerPort: 8081
      {{ if (.Values.dockerSecret)}}
      imagePullSecrets:
      - name: {{ .Values.dockerSecret }}
      {{ end }}
status: {}
