apiVersion: apps/v1
kind: Deployment
metadata:
  name: connector
  labels:
    service: connector
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      service: connector
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: connector
      # used for local development to always upgrade the
      # deployment when running helm upgrade
      # TODO revist for production deployments
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          name: connector
          command: ["cape"]
          args: ["connector", "start"]
          ports:
            - containerPort: {{ .Values.port }}
          env:
            - name: CAPE_COORDINATOR_URL
              value: {{ .Values.coordinator_url }}
            - name: CAPE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.token_secret }}
                  key: token
      {{ if (.Values.dockerSecret)}}
      imagePullSecrets:
        - name: {{ .Values.dockerSecret }}
      {{ end }}
status: {}
