apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: connector
  labels:
    service: connector
spec:
  replicas: 1
  strategy:
    rollingUpdate:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: connector
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: Always
        name: connector
        command: ["./privacy", "connector", "start"]
        ports:
        - containerPort: 8080
      {{ if (.Values.dockerSecret)}}
      imagePullSecrets:
      - name: {{ .Values.dockerSecret }}
      {{ end }}
status: {}