name: Main
on: [push]
jobs:
  build:
    services:
      postgres:
        image: postgres:11.7-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: dev
          POSTGRES_DB: postgres
        ports:
        # will assign a random free host port
        - 5432/tcp
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    name: Build & Test
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v1
    - name: Build Testing Container
      run: make docker-ci
